### ISSUE TITLE
Support for Image Transform

### ISSUE THREAD

**Issue by livingtech** [HuttchDev/craft-webpme#1]
Hello there,

I have used your plugin for many websites and I wanted to ask if there is a way to add support for transform images. As you probably know, they are different to integrate in template than normal images and as for now, I don't think the plugin has a support for them.

**Comment by HuttchDev** [comment]
Hello there,

Thank you for using our plugin :)

Regarding support for preset Image Transforms made in the CMS admin panel, you can pass the image transform handle with:
```
WebP(image, { transform: '<transform handle here>' })
```
or to apply overrides to the preset:
```
WebP(image, { transform: '<transform handle>', quality: 80, position: 'center-bottom' })
```

I have updated the readme to help clarify the different options and params available as it was no clear.

Please let me know if this has solved your question or if i have misunderstood.
